-- SUROKKHA AI BD - PDF hospital/facility import
-- Source: all_hospitals_list_19-Aug(2).pdf
-- 251 records extracted from the supplied PDF.
-- verified=TRUE is set because the user confirmed the PDF data is verified.
-- last_verified_at remains NULL because the PDF has no explicit verification timestamp.
BEGIN;
ALTER TABLE healthcare_facilities ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE healthcare_facilities ADD COLUMN IF NOT EXISTS email TEXT;

INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('1','Aalok Healthcare & Hospital Ltd',NULL,NULL,'Hospital','Dhaka','Dhaka','House- 1 & 3 , Road-2, Block-B, Mirpur-10, Dhaka-1216','Unknown','Accounts and Billing: 01322-896902, Hotline: 01919-224895',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'House- 1 & 3 , Road-2, Block-B, Mirpur-10, Dhaka-1216','aalokbd195@gmail.com');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('2','Aalok Healthcare and Foundation Hospital',NULL,NULL,'Hospital','Dhaka','Tangail','Hospital Gait, Ghatail, Tangail','Unknown','Urmi- 01769 969869, Hotline: 01769- 969869, 01769-969845',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'Hospital Gait, Ghatail, Tangail','aalokghatail2018@gmail.com');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('3','Aalok Healthcare Ltd',NULL,NULL,'Diagnostic Center','Dhaka','Dhaka','21 Darus Salam Road, Mirpur 1, Dhaka- 1216','Unknown','Hotline: 01769969840, 01769969858 Accounts and Billing: 01322-896902',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'21 Darus Salam Road, Mirpur 1, Dhaka- 1216','aalokbd195@gmail.com');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('4','Aalok Healthcare Ltd',NULL,NULL,'Diagnostic Center','Dhaka','Tangail','Hospital Gate, Ghatail, Tangail','Unknown','Pathological Tests - 25% Radiology & Imaging-20% N/A Md. Ainal Mobile: 01769969815, 01769969869',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'Hospital Gate, Ghatail, Tangail','N/A');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('5','Aalok Healthcare Ltd , Pallabi',NULL,NULL,'Diagnostic Center','Dhaka','Dhaka','2/6 Pallabi,(111/2, Bus Stand), Mirpur, Dhaka','Unknown','Manager: 01769-969853 , Accounts and Billing: 01322-896902',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'2/6 Pallabi,(111/2, Bus Stand), Mirpur, Dhaka','aalok195@yahoo.com');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('6','Aalok Healthcare Ltd, Branch - 4, Kochukhet',NULL,NULL,'Diagnostic Center','Dhaka','Dhaka','Rajanigandha Tower, Kachukhet, Dhaka Cant.','Unknown','Pathological Tests - 25% Radiology & Imaging-20% N/A 01769969816, 01725-695669, Accounts and Billing: 01322-896902',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'Rajanigandha Tower, Kachukhet, Dhaka Cant.','N/A');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('7','Aalok Healthcare Ltd, Branch 6 Mohakhali',NULL,NULL,'Diagnostic Center','Dhaka','Dhaka','Mohakhali SAHIC, Dhaka','Unknown','Pathological Tests - 25% Radiology & Imaging-20% N/A 01769-969842 , Accounts and Billing: 01322-896902',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'Mohakhali SAHIC, Dhaka','N/A');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('8','Aalok Hospital Ltd.',NULL,NULL,'Hospital','Dhaka','Dhaka','Home-1, Road-5, Block-A, Section-6, Dhaka-1216','Unknown','CASHLESS HOSPITALIZATION Pathological Tests - 25% Radiology & Imaging-20% Discount in Outdoor Services N/A Hotline: 01915-448491, Manager: 01769-969853, 01769-969836-37',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'Home-1, Road-5, Block-A, Section-6, Dhaka-1216','N/A');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('9','Aalok Mother & Child care Centre',NULL,NULL,'Diagnostic Center','Dhaka','Dhaka','House-3,Road-4, Block-A, Section-6,Mirpur','Unknown','Pathological Tests - 25% Radiology & Imaging-20% N/A 01769-969814, 01725-695669 Accounts and Billing: 01322-896902',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'House-3,Road-4, Block-A, Section-6,Mirpur','N/A');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('10','Aichi Hospital Ltd Dhaka',NULL,NULL,'Hospital','Dhaka','Dhaka','35 & 37, Sector-08, Abdullahpur mahasarak, Uttara, Dhaka','Unknown','Amirul: 01552-584764, Hotline: 01711-612103',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'35 & 37, Sector-08, Abdullahpur mahasarak, Uttara, Dhaka','aichi_hospital@yahoo.com');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('11','Al Helal Specialized Hospital Mirpur',NULL,NULL,'Hospital','Dhaka','Dhaka','150, Begum Rokeya Sarani, Senpara- Parbata, Mirpur-10, Dhaka.','Unknown','Shafiqul Talukder: 01711-156001',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'150, Begum Rokeya Sarani, Senpara- Parbata, Mirpur-10, Dhaka.','ahshcorp@gmail.com');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('12','Al Khidmah Diagnostic Complex',NULL,NULL,'Diagnostic Center','Mymensingh','Mymensingh','Main Road, Muktagacachha, Mymensingh','Unknown','Mahfuzul Ahmed : 01728104655',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'Main Road, Muktagacachha, Mymensingh','alkhidmahdiagnostic1980@gmail.com');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('13','Al Modina Diagnostic & Consultation Centre, Joypurhat',NULL,NULL,'Hospital','Rajshahi','Joypurhat','Sadar Rd, Joypurhat , rajhsahi','Unknown','Nasir Hossain: 01724-215526, Hotline: 01957-042288',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'Sadar Rd, Joypurhat , rajhsahi','almadinadiagnostic@gmail.com');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('14','Al Raji Hospital Farmgate',NULL,NULL,'Hospital','Dhaka','Dhaka','14/A, 31/A, Tejkunipara, Tejgaon, Dhaka- 1215','Unknown','Humyun Ahmed: 01712-126603, Hotline: 01718-120249',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'14/A, 31/A, Tejkunipara, Tejgaon, Dhaka- 1215','alrajhihospital6@gmail.com');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('15','Alliance Hospital Limited',NULL,NULL,'Hospital','Dhaka','Dhaka','24/3 Khilji Road, Ring Rd, Dhaka 1207','Unknown','Humayun kabir: 01983-737611, 01720-422448',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'24/3 Khilji Road, Ring Rd, Dhaka 1207','Alliance24@gmail.com');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('16','Anwer Khan Modern Diagnostic Center & Hospital Outdoor Service',NULL,NULL,'Diagnostic Center','Dhaka','Dhaka','Plot: 11, Road: 11, Block: G, Flat: 1/A (1st & 2nd Floor), Banani, Dhaka.','Unknown','Pathological Tests - 25% Radiology & Imaging - 10% Discount in Outdoor Services N/A Mukul: 01711-927861, Hotline: 01705-407170',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'Plot: 11, Road: 11, Block: G, Flat: 1/A (1st & 2nd Floor), Banani, Dhaka.','N/A');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('17','Anwer Khan Modern Medical College',NULL,NULL,'Hospital','Dhaka','Dhaka','Hospital House-17, Road-8, Dhanmondi, Dhaka- 1205','Unknown','01711-927861 , Mukul: 01711-927861 , Helpline: 10652, 09678010652',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'Hospital House-17, Road-8, Dhanmondi, Dhaka- 1205','mukul85bam@gmail.com');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('18','Apollo Clinic (JMI Specialized Hospital Ltd)',NULL,NULL,'Hospital','Dhaka','Dhaka','Dhanmodi Dhaka #64, Satmasjid Road, C/A, Dhaka','Unknown','880 1332 524000',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'Dhanmodi Dhaka #64, Satmasjid Road, C/A, Dhaka','dhanmondi@apolloclinic.com');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('19','APOLLO IMPERIAL HOSPITALS',NULL,NULL,'Hospital','Chattogram','Chattogram','Zakir Hossain Road, Khulshi, Chattogram, 4202.','Unknown','Hot line 09610-847847, 01832- 747270',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'Zakir Hossain Road, Khulshi, Chattogram, 4202.','nfo@aihlbd.org');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('20','Asgar Ali Hospital',NULL,NULL,'Hospital','Dhaka','Dhaka','111/1/A Distillery Road Gandaria, Dhaka- 1204 Bangladesh','Unknown','Mahfuz Bin Hafiz: 01787-683062, Hotline: 01787-683333-35',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'111/1/A Distillery Road Gandaria, Dhaka- 1204 Bangladesh','marufaah@asgaralihospital.com');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('21','B. M Diagnostic Center',NULL,NULL,'Diagnostic Center','Chattogram','Feni','Hospital Road, Ma Nur Jahan Vila, Porsuram, Feni','Unknown','Pathological Tests - 30% Radiology & Imaging - 20% Discount in Outdoor Services N/A 01836-167666',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'Hospital Road, Ma Nur Jahan Vila, Porsuram, Feni','N/A');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('22','Bangladesh Specialized Hospital PLC.',NULL,NULL,'Hospital','Dhaka','Dhaka','21 Shyamoli, Mirpur Road, Dhaka-1207, Bangladesh','Unknown','Fahad: 01313-777888 , Billing: 01313-777977',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'21 Shyamoli, Mirpur Road, Dhaka-1207, Bangladesh','samsul@bshl.com.bd');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('23','Bhairab New Life Medical Center',NULL,NULL,'Diagnostic Center','Dhaka','Kishoreganj','1627/2 Kamalpur, New town, Bhairab, Kishoregonj','Unknown','Md. Hazi Mohorom ali: 01785939244',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'1627/2 Kamalpur, New town, Bhairab, Kishoregonj','newlifemedicalcenter2022@gmail.com');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('24','Bhola Model Hospital & Diagnostic Center',NULL,NULL,'Hospital','Barishal','Bhola','Muslim Para Road, Bhola Sadar Bhola','Unknown','Md. Shahid: 01798-715382 , Hotline: 01759-301173',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'Muslim Para Road, Bhola Sadar Bhola','sahid01828146878@gmail.com');
INSERT INTO healthcare_facilities (external_id,name,name_bn,agency,facility_type,division,district,area,ownership,phone,emergency_phone,verified,source,last_verified_at,active,address,email) VALUES ('25','Bhuiyan Clinic (Digital Diagnostic & Consultation Center)',NULL,NULL,'Diagnostic Center','Chattogram','Feni','Chowmuhani Road, Dagon Bhuiyan, Feni, Bangladesh','Unknown','Md. Hasan mahmud : 01919008228',NULL,TRUE,'all_hospitals_list_19-Aug(2).pdf',NULL,TRUE,'Chowmuhani Road, Dagon Bhuiyan, Feni, Bangladesh','hasanmahmud23@gmail.com');
